export const genreData = {
    "genre":[
      "fantasy",
      "romance",
      "mystery",
      "dystopian",
      "horror",
      "plot twist",
      "creative",
    ],
    "fantasy":[
      "A world of people born into magnificent powers where bloodshed controls life",
      "A mortal has been accidentally placed onto Olympus.",
      "Everyone is born with three wishes in life that they are not allowed to use until (input age here).",
      "A contest for the queen after the sudden death of said queen from a magical realm.",
      "The bridge between the realm of the fae and mortal shrinks with each day while tensions run high.",
      "You are the first and last person to discover the fountain of youth.",
      "You have lived for (insert time) but have run into the option to finally be set to rest, but (blank) makes you question what you truly want",
      "You have lived many lifetimes, always in an endless cycle of birth and death, you finally find someone the same though",
      "Each night you are woken by the shouts of sailors and deckhands, the ringing of bells, and the light. But no one else has seen or heard such things",
      "Luck has become a hereditary trait",
      "Imaginary friends have gone too far, now that friend is real… but something is totally off",
      "“Familiars” play pivotal roles in society, the strength of said creature determines your fate",
    ],
    "romance":[
      "You fall in love with an immortal who finds you each lifetime. You find this out by a photo album of all their “exes” who all look similar to you.",
      "She’s a world-class thief, he’s the lead investigator. At each crime scene, there’s a note left just for him.",
      "He’s rich beyond anyone’s wildest dreams and no one has ever been able to get close to him. All he cares about in life is perfection which he always is looking for in artwork and whatnot. But then an unruly, perfectly imperfect girl bumps into him, ruining the vase he’s bought while at a show.",
      "She has no care for love, all she cares about is ruling with an iron fist, making her the fearsome but prosperous boss nationwide. Her newest hire has all the skills needed and perfect in every aspect, but then she’s discovered to be sent by her rival… what will she do?",
      "She’s motivated by blood and money and will take nearly any contract if there’s enough cash involved; he is to be the victim. But when one contract killer is trying to kill the other, what will occur?",
      "In his kingdom, it is to be a queen that always rules. However, when both his parents are murdered, to keep some unpleasant relatives off the throne he must change his entire identity to be the new queen. This includes marrying the prince of another kingdom…",
      "He ensures that everyone finds their soulmate, sometimes through much trial and error. All he’s ever done is watch idly by, but when he falls in love with a mortal meant for someone else, what is he to do?",
      "She’s a writer, one that writes about love and death. One night she gets a call from someone who says and acts exactly as one of her characters did… alarmed she continues to contact this person. Soon enough she finds herself in love with the character…",
      "She expects and wants everything to go exactly like all the fairytale stories she heard when she was younger, always with expectations high whilst being often the laughingstock. But then, she meets him…",
      "Everyone knows their fate, hers is quite bleak. She has no motivation and low expectations because of it, but then she is mistaken for someone else. And when she is mistaken to be who she’s not, he comes into her life and finds herself with everything she was never supposed to have.",
      "His father is quite literally (some well-known character that would cause problems, ex: the devil, Frankenstein/ doctor Frankenstein, Vampire/Werewolf, etc.), making him a total outcast. When a new girl who heeds no warnings approaches him, what will he do?",
      "Their relationship was fake or at least supposed to be anyhow.",
      "She began getting strange letters in her mail, they were yellowed and very old looking, but somehow well preserved all the same even though appearing to be from centuries ago. She eventually decides to write one back, and he receives it. They’re centuries apart but sure they’re soul mates.",
    ],
    mystery:[
      "You dream of murders to happen with minor details, can you save them in time? And why you?",
      "You can’t figure out whether you’re awake or asleep.",
      "You have woken up after a terrible accident, at least that’s what everyone has told you. No one seems to be willing to give any details and you can’t remember the last year of your life…",
      "You could’ve sworn that someone tapped you on the shoulder, but no one was there. As well you feel watched, and then you receive a letter.",
      "A few months ago, you began to sleepwalk, but it’s not only you, but it also seems the entire town is as well.",
      "As you’re restoring a painting you notice something strange, an engraving and the details seem to be changing.",
      "A crime has occurred, more specifically a murder. The victim was found poisoned at the scene and as if they were sleeping, next to a bitten apple… and they were dressed as snow white. Will more follow?",
      "A picture is worth a thousand words, or at least that’s what they say. This one was certainly worth more than that.",
      "A box of pictures fell onto you as you bumped a shelf, it showed a person in each and seemed to go back quite a long time… but in each, the same cat sat.",
      "People believed to be dead or lost for years have started to show up as if they never left with no recollection of where they went either.",
    ],
    dystopian:[
      "A new law allows a person to kill someone once in their lifetime, they must fill out documents on it of course… but as well notify the soon to be victim.",
      "People are now able to quite literally bet their lives when gambling now.",
      "In a desperate hope to cut down on crime and population, those convicted are now entered into a lottery of sorts, the prize? Death. Those with more convictions or worse crimes have a higher likelihood of being chosen.",
      "No one remembers why the walls were built, no one wishes to leave either though.",
      "Black Friday has turned into a “game” for the rich. They throw trinkets and cash to the crowds of those poorer to watch the bloodbath that ensues.",
      "Due to the high-cost and overcrowding of prisons, the government has sent prisoners to man-made islands of which there is no escape. Each island is for a certain level of prisoner, they are left to create their own society or kill each other, whichever works, I guess.",
      "It is now rare for twins to be born, and when they are born it most often is due to one that is meant to stop the other.",
      "A very rare few are born without emotions; it is possible though for others to donate emotions for a time.",
      "Physical traits are achieved through personality. Over time good deeds will create beauty.",
      "Reincarnation is a real thing, and there are bounty hunters to track down these people. They may have been lovers, criminals, etc.",
      "The ability to see color is a privilege of the aristocratic.",
      "Only the smart, strong, and stunningly gorgeous survive. Everyone else is put to death to control the population.",
      "Sometimes news stations find themselves lacking, that’s why you were born. You’re what they call a Joker, your entire purpose is to do all that will make for a great story.",
      "It is now possible to entirely swap bodies with someone else. Of course, this always results in the death of who you’re swapping with.",
      "It is illegal to look outside from the time 11:07 pm to 6:07 am. Each person is required to enter a windowless room for those times in which the government has the ability to lock and unlock the door.",
      "The earth turns out to be a sanctuary for an endangered species, humans. Today is the first day they are to be introduced back into the wild.",
    ],
    history:[
      "As the murderer in this one, you had expected them to split up, go down in hysterics, even to be at each other’s throats. Never that they would start hunting you down.",
      "As an assassin with a sixth sense, you seek vengeance for the restless souls.",
      "You’re a sleepwalking murderer, but when you wake up, you’re a well-known and renowned detective. You’re hunting yourself and others.",
      "In the future virtual reality is more prevalent and even realistic than it’s ever been, an entirely new world and life. It’s often used on high profile criminals to make them live what they did from the victim’s view or their worst nightmare.",
      "You’re finally meeting your “soulmate’s” parents, thrilled and full of glee. But as they close the door behind you, they lean in to whisper, “I’m sorry” / “Forgive me”.",
      "You’ve been noticing strange things when you awake, new marks or stains, objects moved, new, or even missing. So, you set up a camera. After a few weeks of going over the footage, there’s something strange and unnerving.",
      "She never seems to be able to get it right. She can’t seem to find “the one”, or someone even close to that. Little does she know it’s been the same… creature, a shapeshifter who at all costs will have her.",
      "Each night you heard a tapping on the glass or shrill noise. One night it was too loud to ignore and persisted… soon you realized it was coming from the…",
      "It’s 3:33 am, a blaring siren comes from your phone with an official notification: Do not look at the moon, do not even glance at it. As well there’s an unbelievable amount of texts and posts on social media saying in some way that it’s a must-see, stunningly beautiful, once in a lifetime view.",
      "“The human mind is truly the most horrifying and gruesome thing of all.”",
      "The crow counting rhyme: One for sorrow / Two for mirth / Three for a wedding / and Four for a birth / Five for silver / Six for gold / and Seven for a secret not to be told. There are also many variations of this rhyme that you could use instead, sets up for an interesting and creepy story though.",
      "The last thing I saw was the glow of my alarm clock, 3:00 am, and then (something scary, death, creature, etc.) ex: its long and sharp rotting nails slowly tore through my neck, its other “hand” muffling my screams. I then woke up in a cold sweat and glanced at the clock, 2:59 am… and that’s when I heard a creaking and smelled of rot.",
      "It is now possible to know some details of your past lives, how many, how long you lived, etc. As well it’s been linked that some of your phobias are how you died…",
      "You’re on edge, a few weeks ago you there would be some weird occurrence. Then it was a note with messy and illegible writing. Now you can hear shrill noises, screams, shouting, indistinct. Now at seemingly the source of a scratching noise etched is a clear warning.",
      "An anonymous admirer letter was slipped under your door at your college. It would seem cute and sweet if it hadn’t been from your closet.",
      "I found a dead body in my trunk today… I could’ve sworn that I had more than that in there just yesterday.",
      "Every night you visit me, sometimes in a dream, sometimes in my nightmares.",
      "I kissed my wife and darling daughter goodnight… and then I awoke in a white padded room with a straight jacket on. They told me it was all just a dream.",
    ],
    "plot twist":[
      "Write from the perspective of one character, but at some point, make it out to all be a dream/ simulation/ drug-induced. It could be good for thrillers or fantasy.",
      "The princess saves the prince.",
      "Write a story where one of your characters either from the start or at some point in the book are dead or presumed dead. Then have it be that they never were to shake up the story.",
      "A character that keeps telling outlandish things, but it turns out they’re right.",
      "A main character or “essential” character killed out of nowhere.",
      "Have a very guilty and easy to hate a character in your story, have it be a double-cross or frame job.",
      "A character who is mistaken for someone else but goes along with it.",
      "A character is revealed to not be what they or the audience had thought.",
      "An important character throughout the plot is revealed to never have truly existed.",
      "Some devastating occurrence is caused by those whose entire goal was to fix it or keep it from occurring.",
      "A character believed to be unimportant to quite bland turns out to be essential and far from.",
      "Something the character has been searching for or desperately needed was right in front of their eyes the entire time.",
      "Have it turn out to be that the entire time some blackmail has been the cause for nearly all of a character’s actions.",
      "A character who is absolutely in love/ obsessed/ or infatuated with another learns it’s for the wrong reasons/ that they’re not at all what they seemed/ etc.",
      "It turns out the character or group of characters have been led to helping the enemy.",
    ],
    "creative":[
      "Make a hero or protagonist that most will hate, vice versa for an antagonist or villain.",
      "Truth or Dare, your character has a secret, or a truth. What are they willing to say or do to keep said truth secret.",
      "“I love you.”, “Lying isn’t a good look for you.”",
      "A bunch of short stories that end on major cliffhangers, but a final one. Once you’re done writing those maybe have them somehow all connect or give the ending to each.",
      "Everyone ages up until a certain age (ex: 18, 21, etc.) and will remain that age until they meet their soulmate. (Could be used as someone avoiding finding theirs to reign forever, or accidentally aging, or finding you aren’t aging even when with someone.)",
      "A high school group can’t agree on the meaning and interpretation of Romeo and Juliet, so of course they split into two groups. But then, one person from one group falls in love with the other. Even though it seems nearly every Shakespeare is going on in the group at the same time.",
      "The retelling of Snow White, if she truly had lips red as a rose, hair black as ebony, and skin white as snow.",
      "A world where everyone is born with a unique tattoo that gives a hint to fate, personality, each person they love their tattoos will begin to form somewhere on them. These tattoos cannot be removed and will not go away, though they can be hidden and covered. They will receive a tattoo or mark for each love they have, it does not matter if they no longer do or what happens.",
      "A customer-service worker (retail, support, etc.) who quits their day job to deal with demons, ghosts, and whatnot.",
      "A story on vampires, but not all are the usual sophisticated, well mannered, well spoken, and so on. Instead, they do their best to not seem outdated, may mercilessly mix multiple slang from way to many different eras, or talking in laughable applications of slang and references, etc.",
      "Vampires, but for once there are those who’ve been turned other than around nineteen or twenty. With some being turned as a child or while elderly.",
      "A world where all the mythical creatures or monsters, etc., exist and try to coexist. Each with their own job, talent, and so on. Trying to live “normally”.",
      "Cinderella went to the ball to murder the prince. Retellings of well-known fairy tales.",
      "A “superhero” and “villain” who are roommates and nemesis. (Could be they don’t know about the other so both are lying, they both know but don’t want to give away themselves, so on)",
      "A twist on the changeling stories. A mother caught a fair attempting to switch the child with a changeling soon after the arrival of her child. So she is unable to tell them apart, raises both. Both twins are exactly identical in voice and appearance.",  
    ]
  };
  